### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by eeluo** [BinqingWu/2019ZJU_SummerCamp#2]
Could you please tell me what's your original dataset? It seems like you directly calculate the data.csv from the POIs data?

**Comment by water-wbq** [comment]
POI用于计算节点间的相似度矩阵weight_simi.csv，来源是在OriginalData目录中的1129PointsPOI.csv。data.csv里面是30个节点40天内的叫车需求,来源是OriginalData中30Points40DaysDemand。

以上所有数据都是小规模的测试数据，仅供交流学习，完整的数据目前我也没有。

**Comment by eeluo** [comment]
> 
> 
> POI用于计算节点间的相似度矩阵weight_simi.csv，来源是在OriginalData目录中的1129PointsPOI.csv。data.csv里面是30个节点40天内的叫车需求,来源是OriginalData中30Points40DaysDemand。
> 
> 以上所有数据都是小规模的测试数据，仅供交流学习，完整的数据目前我也没有。

好的好的，谢谢你

**Comment by eeluo** [comment]
> 
> 
> POI用于计算节点间的相似度矩阵weight_simi.csv，来源是在OriginalData目录中的1129PointsPOI.csv。data.csv里面是30个节点40天内的叫车需求,来源是OriginalData中30Points40DaysDemand。
> 
> 以上所有数据都是小规模的测试数据，仅供交流学习，完整的数据目前我也没有。

请问一下，您是不是没有上传根据经纬度划分网格区域并统计订单数量的代码呀？我是新手，不太懂怎么操作，想请问您有这部分代码吗？我想学习一下，谢谢您！

**Comment by water-wbq** [comment]
你指的是每个节点的订单数据是如何为得到的吗，比如/OriginalData/30Points40DaysDemand/20170101.csv是如何得到？还是说在这个的基础上再划分网格进行订单统计？
如果是前者，由于这些数据我是从一个已经毕业的学长那里拿到的，所以根据“经纬度划分网格区域并统计订单数量的代码”我是没有写的。如果是后者，单从这个模型实现角度应该是不需要再进行统计的，所以我也没有写。
那如果你有实现”根据经纬度划分网格区域并统计订单数量“的需求，可以for循环+条件判断来判断某节点是否属于你规定的格子内，再把它map到各个节点和时间点以完成全部节点在各个时间点的统计。这部分处理方式在”轨迹处理“、”栅格数据“相关的代码里出现的比较多。

**Comment by eeluo** [comment]
> 
> 
> 你指的是每个节点的订单数据是如何为得到的吗，比如/OriginalData/30Points40DaysDemand/20170101.csv是如何得到？还是说在这个的基础上再划分网格进行订单统计？
> 如果是前者，由于这些数据我是从一个已经毕业的学长那里拿到的，所以根据“经纬度划分网格区域并统计订单数量的代码”我是没有写的。如果是后者，单从这个模型实现角度应该是不需要再进行统计的，所以我也没有写。
> 那如果你有实现”根据经纬度划分网格区域并统计订单数量“的需求，可以for循环+条件判断来判断某节点是否属于你规定的格子内，再把它map到各个节点和时间点以完成全部节点在各个时间点的统计。这部分处理方式在”轨迹处理“、”栅格数据“相关的代码里出现的比较多。

好的，很感谢您的耐心回答！我自己再去学习学习，非常感谢！

**Comment by James23forever** [comment]
您好，/OriginalData/30Points40DaysDemand/20170101.csv请问这个数据具体是什么？是怎么规定的？

**Comment by James23forever** [comment]
0,76,6,7,0,15,0,0,30,19,0,1,0,36,25,9,15,13,14,19,0,15,39,23,31,0,53,7,0,0比如第一行每个数字是几小时的需求还是什么？

**Comment by James23forever** [comment]
能加一下您的微信吗？我的微信是15840023429
